/**
 * snapshot-diff.ts — Compare two subscription snapshots and report differences.
 *
 * Detects:
 *   - New subscribers (present in after, absent in before)
 *   - Removed subscribers (present in before, absent in after)
 *   - Modified subscriptions (present in both, but fields changed)
 *
 * Usage:
 *   npx tsx scripts/snapshot-diff.ts <before.json> <after.json> [--field <name>]
 *
 * Flags:
 *   --field <name>   Filter diff output to a specific field
 *                    (amount, interval, active, paused, merchant, token)
 *
 * Exit codes:
 *   0 — no differences found
 *   1 — differences found (useful for CI post-upgrade checks)
 *   2 — usage / file errors
 *
 * ## Summary Output
 *   "X new, Y removed, Z modified subscriptions"
 *
 * ## Snapshots
 *   Snapshots are generated by subscription-snapshot.ts and use the schema:
 *   {
 *     generated_at, contract, network, count,
 *     subscriptions: [{ address, found, active, paused, amount, interval,
 *                       last_charged, next_charge_at, merchant, token }]
 *   }
 */

import { readFileSync } from "node:fs";

// ── Types ────────────────────────────────────────────────────────────────────

/**
 * Shape of a single subscription entry in the snapshot (matches
 * subscription-snapshot.ts output).
 */
interface SubscriptionEntry {
  address: string;
  found: boolean;
  active?: boolean;
  paused?: boolean;
  amount?: string;
  interval?: string;
  last_charged?: string;
  next_charge_at?: string;
  merchant?: string;
  token?: string;
}

/** Full snapshot file format. */
interface Snapshot {
  generated_at: string;
  contract: string;
  network: string;
  count: number;
  subscriptions: SubscriptionEntry[];
}

/**
 * A single field-level change within a modified subscription.
 */
interface FieldChange {
  field: string;
  before: unknown;
  after: unknown;
}

/**
 * Complete record of a modified subscription.
 */
interface Modification {
  address: string;
  changes: FieldChange[];
}

/**
 * Aggregated diff result.
 */
interface DiffResult {
  snapshotBeforePath: string;
  snapshotAfterPath: string;
  generatedBefore: string;
  generatedAfter: string;
  contractBefore: string;
  contractAfter: string;
  newSubscribers: SubscriptionEntry[];
  removedSubscribers: SubscriptionEntry[];
  modifiedSubscriptions: Modification[];
}

// ── Comparable fields ────────────────────────────────────────────────────────

/**
 * Subscription fields that are compared during diffing.
 * Fields like address, found, last_charged, next_charge_at are excluded
 * because next_charge_at is derived from last_charged+interval.
 */
const COMPARED_FIELDS: Array<keyof SubscriptionEntry> = [
  "active",
  "paused",
  "amount",
  "interval",
  "merchant",
  "token",
];

/**
 * Validate that a --field value is one of the comparable fields.
 */
function isValidField(field: string): field is keyof SubscriptionEntry {
  return (COMPARED_FIELDS as string[]).includes(field);
}

// ── File loading ─────────────────────────────────────────────────────────────

/**
 * Load and parse a snapshot JSON file. Exits on any error.
 */
function loadSnapshot(path: string): Snapshot {
  let raw: string;
  try {
    raw = readFileSync(path, "utf-8");
  } catch {
    console.error(`ERROR: Cannot read snapshot file: ${path}`);
    process.exit(2);
  }

  let data: unknown;
  try {
    data = JSON.parse(raw);
  } catch (e) {
    console.error(
      `ERROR: Invalid JSON in snapshot file: ${path}\n  ${(e as Error).message}`,
    );
    process.exit(2);
  }

  const snapshot = data as Snapshot;
  if (!snapshot.subscriptions || !Array.isArray(snapshot.subscriptions)) {
    console.error(
      `ERROR: Snapshot file missing 'subscriptions' array: ${path}`,
    );
    process.exit(2);
  }

  return snapshot;
}

// ── Diff engine ──────────────────────────────────────────────────────────────

/**
 * Build a lookup map of found subscriptions keyed by address.
 * Subscriptions with `found: false` are excluded.
 */
function buildSubscriptionMap(
  subscriptions: SubscriptionEntry[],
): Map<string, SubscriptionEntry> {
  const map = new Map<string, SubscriptionEntry>();
  for (const sub of subscriptions) {
    if (sub.found) {
      map.set(sub.address, sub);
    }
  }
  return map;
}

/**
 * Compare two subscription entries field-by-field and return a list of
 * changes. Only compares fields in COMPARED_FIELDS.
 *
 * Optionally filtered to a single field via `fieldFilter`.
 */
function diffSubscriptionFields(
  before: SubscriptionEntry,
  after: SubscriptionEntry,
  fieldFilter?: keyof SubscriptionEntry,
): FieldChange[] {
  const changes: FieldChange[] = [];

  for (const field of COMPARED_FIELDS) {
    if (fieldFilter && field !== fieldFilter) continue;

    const a = before[field];
    const b = after[field];

    // Treat undefined and empty string as equivalent for optional fields
    const normA = a === undefined || a === "" ? undefined : a;
    const normB = b === undefined || b === "" ? undefined : b;

    if (!deepEqual(normA, normB)) {
      changes.push({
        field,
        before: normA ?? "(none)",
        after: normB ?? "(none)",
      });
    }
  }

  return changes;
}

/**
 * Simple strict equality for primitive types. All subscription fields are
 * strings, booleans, or undefined — no deep comparison needed.
 */
function deepEqual(a: unknown, b: unknown): boolean {
  return a === b;
}

/**
 * Compute the full diff between two snapshots.
 */
function diffSnapshots(
  before: Snapshot,
  after: Snapshot,
  fieldFilter?: keyof SubscriptionEntry,
): DiffResult {
  const beforeMap = buildSubscriptionMap(before.subscriptions);
  const afterMap = buildSubscriptionMap(after.subscriptions);

  const beforeAddresses = new Set(beforeMap.keys());
  const afterAddresses = new Set(afterMap.keys());

  // New: in after but not in before
  const newAddresses = new Set(
    [...afterAddresses].filter((a) => !beforeAddresses.has(a)),
  );

  // Removed: in before but not in after
  const removedAddresses = new Set(
    [...beforeAddresses].filter((a) => !afterAddresses.has(a)),
  );

  // Intersection: check for modifications
  const intersection = new Set(
    [...beforeAddresses].filter((a) => afterAddresses.has(a)),
  );

  const modified: Modification[] = [];
  for (const addr of intersection) {
    const changes = diffSubscriptionFields(
      beforeMap.get(addr)!,
      afterMap.get(addr)!,
      fieldFilter,
    );
    if (changes.length > 0) {
      modified.push({ address: addr, changes });
    }
  }

  return {
    snapshotBeforePath: "",
    snapshotAfterPath: "",
    generatedBefore: before.generated_at,
    generatedAfter: after.generated_at,
    contractBefore: before.contract,
    contractAfter: after.contract,
    newSubscribers: [...newAddresses].map((a) => afterMap.get(a)!),
    removedSubscribers: [...removedAddresses].map((a) => beforeMap.get(a)!),
    modifiedSubscriptions: modified,
  };
}

// ── Output formatting ────────────────────────────────────────────────────────

/**
 * Truncate a Stellar address for display: first 8 + … + last 4.
 */
function shortAddr(addr: string): string {
  if (addr.length <= 16) return addr;
  return `${addr.slice(0, 8)}…${addr.slice(-4)}`;
}

/**
 * Format a field value for display.
 */
function fmtVal(v: unknown): string {
  if (typeof v === "string" && v.length > 44) return shortAddr(v);
  return String(v);
}

/**
 * Print the diff result to stdout in a human-readable format.
 */
function printDiff(result: DiffResult, fieldFilter?: string): void {
  const { newSubscribers, removedSubscribers, modifiedSubscriptions } = result;
  const hasChanges =
    newSubscribers.length > 0 ||
    removedSubscribers.length > 0 ||
    modifiedSubscriptions.length > 0;

  // ── Header ──────────────────────────────────────────────────────────────
  console.log("═══════════════════════════════════════════════════");
  console.log("  Subscription Snapshot Diff");
  console.log("═══════════════════════════════════════════════════");
  console.log(`  Before : ${result.generatedBefore}`);
  console.log(`  After  : ${result.generatedAfter}`);
  console.log(`  Contract before: ${result.contractBefore}`);
  console.log(`  Contract after : ${result.contractAfter}`);

  // Note block-height differences
  if (result.contractBefore !== result.contractAfter) {
    console.log("  ⚠  Contract ID differs between snapshots.");
  }
  if (result.generatedBefore !== result.generatedAfter) {
    console.log("  ℹ  Snapshots taken at different times.");
  }
  console.log("");

  if (!hasChanges) {
    console.log("  ✓ No differences found.");
    console.log("");
    return;
  }

  // ── New subscribers ─────────────────────────────────────────────────────
  if (newSubscribers.length > 0) {
    console.log(`  🆕 NEW SUBSCRIBERS (${newSubscribers.length})`);
    console.log("  ─────────────────────────────────────────");
    for (const sub of newSubscribers) {
      console.log(`    ${shortAddr(sub.address)}`);
      if (!fieldFilter || fieldFilter === "active")
        console.log(`      active   : ${sub.active ?? "(none)"}`);
      if (!fieldFilter || fieldFilter === "amount")
        console.log(`      amount   : ${sub.amount ?? "(none)"}`);
      if (!fieldFilter || fieldFilter === "interval")
        console.log(`      interval : ${sub.interval ?? "(none)"}`);
      if (!fieldFilter || fieldFilter === "merchant")
        console.log(
          `      merchant : ${sub.merchant ? shortAddr(sub.merchant) : "(none)"}`,
        );
      if (!fieldFilter || fieldFilter === "token")
        console.log(
          `      token    : ${sub.token ? shortAddr(sub.token) : "(none)"}`,
        );
    }
    console.log("");
  }

  // ── Removed subscribers ─────────────────────────────────────────────────
  if (removedSubscribers.length > 0) {
    console.log(`  ❌ REMOVED SUBSCRIBERS (${removedSubscribers.length})`);
    console.log("  ─────────────────────────────────────────");
    for (const sub of removedSubscribers) {
      console.log(`    ${shortAddr(sub.address)}`);
    }
    console.log("");
  }

  // ── Modified subscriptions ──────────────────────────────────────────────
  if (modifiedSubscriptions.length > 0) {
    const fieldLabel = fieldFilter ? ` (field: ${fieldFilter})` : "";
    console.log(
      `  ✏️  MODIFIED SUBSCRIPTIONS (${modifiedSubscriptions.length})${fieldLabel}`,
    );
    console.log("  ─────────────────────────────────────────");
    for (const mod of modifiedSubscriptions) {
      console.log(`    ${shortAddr(mod.address)}`);
      for (const change of mod.changes) {
        const b = fmtVal(change.before);
        const a = fmtVal(change.after);
        console.log(`      ${change.field}: ${b} → ${a}`);
      }
    }
    console.log("");
  }

  // ── Summary ─────────────────────────────────────────────────────────────
  console.log(
    `  SUMMARY: ${newSubscribers.length} new, ${removedSubscribers.length} removed, ${modifiedSubscriptions.length} modified subscriptions`,
  );
  console.log("");
}

// ── CLI argument parsing ─────────────────────────────────────────────────────

function parseArgs(): {
  beforePath: string;
  afterPath: string;
  fieldFilter?: keyof SubscriptionEntry;
} {
  const args = process.argv.slice(2);

  // Check for --field flag
  const fieldIdx = args.indexOf("--field");
  let fieldFilter: keyof SubscriptionEntry | undefined;
  if (fieldIdx !== -1) {
    const rawField = args[fieldIdx + 1];
    if (!rawField) {
      console.error("ERROR: --field requires a value");
      console.error(`  Valid fields: ${COMPARED_FIELDS.join(", ")}`);
      process.exit(2);
    }
    if (!isValidField(rawField)) {
      console.error(
        `ERROR: Invalid --field value: "${rawField}". Valid fields: ${COMPARED_FIELDS.join(", ")}`,
      );
      process.exit(2);
    }
    fieldFilter = rawField;
    // Remove --field and its value from args for positional parsing
    args.splice(fieldIdx, 2);
  }

  if (args.length < 2) {
    console.error(
      "Usage: npx tsx scripts/snapshot-diff.ts <before.json> <after.json> [--field <name>]",
    );
    console.error("");
    console.error("  --field <name>  Filter diff to a specific field");
    console.error(
      `                  Valid fields: ${COMPARED_FIELDS.join(", ")}`,
    );
    process.exit(2);
  }

  return { beforePath: args[0], afterPath: args[1], fieldFilter };
}

// ── Main ─────────────────────────────────────────────────────────────────────

function main(): void {
  const { beforePath, afterPath, fieldFilter } = parseArgs();

  const before = loadSnapshot(beforePath);
  const after = loadSnapshot(afterPath);

  const diff = diffSnapshots(before, after, fieldFilter);
  diff.snapshotBeforePath = beforePath;
  diff.snapshotAfterPath = afterPath;

  printDiff(diff, fieldFilter);

  const totalChanges =
    diff.newSubscribers.length +
    diff.removedSubscribers.length +
    diff.modifiedSubscriptions.length;

  process.exit(totalChanges > 0 ? 1 : 0);
}

main();
